# Generated by Django 6.0.1 on 2026-02-01 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nom complet')),
                ('email', models.EmailField(max_length=254, verbose_name='Adresse e-mail')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Téléphone')),
                ('subject', models.CharField(choices=[('startup', 'Startup & Entrepreneur'), ('pme', 'PME & ETI'), ('projet', 'Porteur de projet'), ('association', 'Association & ONG'), ('autre', 'Autre')], default='autre', max_length=50, verbose_name='Type de projet')),
                ('message', models.TextField(verbose_name='Message / Description du projet')),
                ('status', models.CharField(choices=[('new', 'Nouvelle demande'), ('contacted', 'Contacté'), ('in_progress', 'En cours de traitement'), ('completed', 'Traité'), ('cancelled', 'Annulé')], default='new', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('notes', models.TextField(blank=True, verbose_name='Notes internes')),
            ],
            options={
                'verbose_name': 'Demande de contact',
                'verbose_name_plural': 'Demandes de contact',
                'ordering': ['-created_at'],
            },
        ),
    ]
